// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskLibrary.Infrastructure.Task;

#nullable disable

namespace TaskLibrary.Infrastructure.Migrations;

[DbContext(typeof(TaskLibraryDbContext))]
partial class TaskLibraryDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("TaskLibrary.Infrastructure.Task.TaskRecord", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("AiReasoning")
                .HasColumnType("text")
                .HasColumnName("ai_reasoning");

            b.Property<string>("AiSuggestedCategory")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("ai_suggested_category");

            b.Property<string>("AiSuggestedPriority")
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("ai_suggested_priority");

            b.Property<bool>("AiSuggestionConfirmed")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(false)
                .HasColumnName("ai_suggestion_confirmed");

            b.Property<string>("Category")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("category");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Description")
                .HasColumnType("text")
                .HasColumnName("description");

            b.Property<string>("Priority")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasDefaultValue("Medium")
                .HasColumnName("priority");

            b.Property<string>("Status")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasDefaultValue("Backlog")
                .HasColumnName("status");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("title");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id");

            b.ToTable("tasks");
        });
#pragma warning restore 612, 618
    }
}
